---
audience: ai
language: en
version: config
purpose: Intelligent trigger configuration
---
version: "1.1"
description: "Guardrail triggers based on file paths and prompts"
config:
  enabled: true
  priority_order: ["critical", "high", "medium", "low"]
  enforcement_default: "suggest"
triggers:
  database-operations:
    priority: critical
    enforcement: block
    description: "Schema or SQL changes"
    file_triggers:
      path_patterns:
        - "db/engines/**/*.sql"
        - "db/engines/**/*.yaml"
        - "migrations/**/*.sql"
    prompt_triggers:
      keywords: ["database", "schema", "migration", "sql"]
    load_documents:
      - path: /db/engines/README.md
        priority: high
      - path: /doc_human/guides/DB_CHANGE_GUIDE.md
        priority: high
      - path: /db/engines/postgres/docs/SCHEMA_GUIDE.md
        priority: medium
  module-development:
    priority: high
    enforcement: suggest
    description: "Creating or restructuring modules"
    file_triggers:
      path_patterns:
        - "modules/*/agent.md"
        - "modules/*/doc/**/*.md"
        - "modules/*/core/**/*"
    prompt_triggers:
      keywords: ["module", "scaffold", "plan"]
    load_documents:
      - path: /doc_human/guides/MODULE_INIT_GUIDE.md
        priority: high
      - path: /doc_human/templates/module-templates/README.md
        priority: medium
  contract-change:
    priority: critical
    enforcement: block
    description: "Breaking API or contract changes"
    file_triggers:
      path_patterns:
        - "modules/*/doc/CONTRACT.md"
        - "tools/**/*.json"
    prompt_triggers:
      keywords: ["contract", "api", "breaking"]
    load_documents:
      - path: /doc_human/templates/module-templates/CONTRACT.md.template
        priority: high
      - path: /doc_agent/quickstart/guardrail-quickstart.md
        priority: high
  production-config:
    priority: critical
    enforcement: block
    description: "Editing production configuration"
    file_triggers:
      path_patterns:
        - "config/prod.yaml"
    prompt_triggers:
      keywords: ["production config", "prod.yaml"]
    load_documents:
      - path: /config/README.md
        priority: high
      - path: /doc_human/guides/CONFIG_GUIDE.md
        priority: high
  staging-config:
    priority: high
    enforcement: warn
    description: "Editing staging configuration"
    file_triggers:
      path_patterns:
        - "config/staging.yaml"
    prompt_triggers:
      keywords: ["staging config"]
    load_documents:
      - path: /config/README.md
        priority: medium
  test-data:
    priority: high
    enforcement: warn
    description: "Modifying fixtures or test data"
    file_triggers:
      path_patterns:
        - "**/fixtures/**/*"
        - "modules/*/doc/TEST_DATA.md"
    prompt_triggers:
      keywords: ["fixture", "test data"]
    load_documents:
      - path: /doc_human/guides/TEST_DATA_STRATEGY.md
        priority: high
  workflow-pattern:
    priority: medium
    enforcement: suggest
    description: "Recommend workflow patterns based on prompts"
    prompt_triggers:
      keywords: ["create module", "fix bug", "database change", "optimize performance", "security audit"]
    load_documents:
      - path: /ai/workflow-patterns/catalog.yaml
        priority: medium
      - path: /ai/workflow-patterns/README.md
        priority: medium
